// Code generated by Slice Machine. DO NOT EDIT.

import dynamic from 'next/dynamic';

export const components = {
  call_to_action: dynamic(() => import('./CallToAction')),
  hero: dynamic(() => import('./Hero')),
  image: dynamic(() => import('./Image')),
  image_cards: dynamic(() => import('./ImageCards')),
  testimonials: dynamic(() => import('./Testimonials')),
  text: dynamic(() => import('./Text')),
  text_with_image: dynamic(() => import('./TextWithImage')),
};
