on:
  push:
    branches:
      - main
      - release/*
jobs:
  lint:
    name: Lint Code
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Node.js v20.10.0
        uses: actions/setup-node@v3
        with:
          node-version: '20.10.0'
          registry-url: https://npm.fontawesome.com/
          scope: '@fortawesome'
          cache: 'npm'

      - name: Install Node Dependencies
        run: npm ci
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_CONFIG_FONT_AWESOME_TOKEN }}

      - name: Build Next.js App
        run: npm run build
